<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <EggIdentityVersion>3.0.0</EggIdentityVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="EggIdentity.Auth" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Brand" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Client" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.CodeStyle" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Contract" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Deploy" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Deploy.AdminUi" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Fallback" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Icons" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Resilience" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Settings" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Settings.AdminUi" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Settings.Api" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Settings.Store" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.Styles" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="EggIdentity.UI" Version="$(EggIdentityVersion)" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="MonorailCss" Version="0.1.3" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
